version: "3.8"

services:
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  services:
    build:
      context: ./service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - MAILER_HOST=sandbox.smtp.mailtrap.io
      - MAILER_PORT=2525
      - MAILER_USER=37872e14f99a20
      - MAILER_PASS=1f650f42f69ff4
      - BROKER_HOST=kafka:9092
