version: "3.8"

services:
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  services:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
    env_file:
      - stack.env

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bradial
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "bradial", "-U", "root"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./database:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - stack.env
    ports:
      - "3000:3000"
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    env_file:
      - stack.env
    ports:
      - "1000:3000"
