@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title [Context] Desafio Bradial

SHOW_PERSON_PORTRAIT()

AddRelTag("dashed", $lineStyle = DashedLine())

Person(user, "Usuário", "Pessoa responsável por cadastrar novos produtos e a movimentação do estoque")
Person(manager, "Gerente", "Pessoa responsável pelo estoque")

System(app, "APP", "Aplicação para gerenciar o estoque de produtos")

System(email, "Serviço de Email", "Sistema para enviar email")

Rel(user, app, "Visualiza e controla o estoque de produtos")
Rel(app, email, "Envia e-mail usando", $tags = "dashed")
Rel(email, manager, "Envia e-mail para", $tags = "dashed")

@enduml
